### ISSUE TITLE
change font awesome icons

### ISSUE THREAD

**Issue by diksha0149** [diksha0149/FindSimran-Website#7]
* icons of section coding problems, contest , resources, login, register, my scream are not matching.

![Screenshot (449)](https://user-images.githubusercontent.com/82230512/227915802-715cb931-2b67-43fb-9319-87cb8c64d5af.png)

**Comment by sreehari212000** [comment]
Hey!
I fixed the issue, but i am getting server error when trying to fork this .
Do you have any idea on why it is coming like that?

**Comment by diksha0149** [comment]
Please do check it once more, It's working now.

**Comment by diksha0149** [comment]
> Hey! I fixed the issue, but i am getting server error when trying to fork this . Do you have any idea on why it is coming like that?

Please do check it again, it's working now.

**Comment by sreehari212000** [comment]
Done!

**Comment by sreehari212000** [comment]
> Issue is icons are not matching the headings.

Oops, I thought the issue is icon and heading not aligning properly.

**Comment by sreehari212000** [comment]
Can you please specify the icons you want instead of the current ones.

**Comment by diksha0149** [comment]
> Can you please specify the icons you want instead of the current ones, or should i change icons accordingly?

You can change it accordingly.

**Comment by sreehari212000** [comment]
![updated](https://user-images.githubusercontent.com/108830784/228129071-57768181-d2e6-4eb4-9688-157a9bdd8422.png)

is this okay?

**Comment by diksha0149** [comment]
> ![updated](https://user-images.githubusercontent.com/108830784/228129071-57768181-d2e6-4eb4-9688-157a9bdd8422.png)
> 
> is this okay?

Yes, Impressive :)

**Comment by diksha0149** [comment]
@sreehari212000  Thank You so much :)

**Comment by sreehari212000** [comment]
> @sreehari212000 Thank You so much :)
You're welcome :D
